# Generated by Django 4.1.13 on 2024-05-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=7)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_off', models.BooleanField(default=False)),
                ('dinner_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dinner_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.subscriptionplan'),
        ),
    ]
