# Generated by Django 4.1.13 on 2024-05-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_timerange_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
